objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterestLeadContactDupCheckTest.cls
@isTest
private  class InterestLeadContactDupCheckTest {
	
	static Lead lead;
	static Contact contact;
	static Interest_Setup__c interestSetup;
	
	static void setup() {
		interestSetup = new Interest_Setup__c(Name='Basketball', Category__c='Sports');
		insert interestSetup;
		contact = new Contact(LastName='ContactName');
		insert contact;
		lead = new Lead(LastName='LeadName', Company='Company', Status='Open - Not Contacted');
		insert lead;
	}
	
	static testMethod void testLeadNotNullContactNotNull(){
		test.startTest();
		setup();
		List<Interest__c> interests = new List<Interest__c>();
		interests.add(
			 new Interest__c(Contact__c = contact.Id, Interest_Setup__c = interestSetup.Id,
						Lead__c = lead.Id));

		for (Interest__c interest: interests) {
			try {
				insert interest;
			}
			catch (Exception e) {
				Boolean expectedExceptionThrown =  e.getMessage().contains('You can not choose both contact and lead.');
				System.AssertEquals(expectedExceptionThrown, true);
			}
		}		
		test.stopTest();
		
	}

	static testMethod void testLeadNullContactNull(){
		test.startTest();
		setup();
		List<Interest__c> interests = new List<Interest__c>();
		interests.add(
			 new Interest__c(Contact__c = null, Interest_Setup__c = interestSetup.Id,
						Lead__c = null));

		for (Interest__c interest: interests) {
			try {
				insert interest;
			}
			catch (Exception e) {
				Boolean expectedExceptionThrown =  e.getMessage().contains('Please choose a contact or a lead.');
				System.AssertEquals(expectedExceptionThrown, true);
			}
		}		
		test.stopTest();
		
	}

	static testMethod void testInterestExist(){
		test.startTest();
		setup();
		List<Interest__c> interests = new List<Interest__c>();
		interests.add(
			 new Interest__c(Contact__c = contact.Id, Interest_Setup__c = interestSetup.Id,
						Lead__c = null));

		interests.add(
			 new Interest__c(Contact__c = contact.Id, Interest_Setup__c = interestSetup.Id,
						Lead__c = null));

		for (Interest__c interest: interests) {
			try {
				insert interest;
			}
			catch (Exception e) {
				Boolean expectedExceptionThrown =  e.getMessage().contains('Interest exists.');
				System.AssertEquals(expectedExceptionThrown, true);
			}
		}		
		test.stopTest();
		
	}
}