objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>Like</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t Like</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterestAddToCampaignExt.cls
public with sharing class InterestAddToCampaignExt {    
    public ApexPages.StandardSetController controller {get; set;}
    public CampaignMember campaignMember {get; set;}
    public Boolean overwrite {get; set;}
    public Boolean noSelection { get; set; }

    public InterestAddToCampaignExt(ApexPages.StandardSetController controller) {
        this.controller = controller;
        campaignMember = new CampaignMember();
       	noSelection = (controller.getSelected().size() == 0);
        if (noSelection) {
        	MessageUtil.writeInfo('Please make your selections form the list view before continue.');
        }
    }

    public PageReference addToCompaign() {   
        Map<Id, CampaignMember> contactMemberMap = new Map<Id, CampaignMember>();
        Map<Id, CampaignMember> leadMemberMap = new Map<Id, CampaignMember>();
        for (Interest__c interest : [Select Notes__c, Name, Interest_Setup__c, Id, Degree__c, Contact__c, Lead__c, Category__c From Interest__c 
            WHERE Id In : controller.getSelected()]) {
            CampaignMember member = new CampaignMember(); 
            member.CampaignId = campaignMember.CampaignId;
            member.Status = campaignMember.Status;
            if (interest.Contact__c != null && !contactMemberMap.keySet().contains(interest.Contact__c)) {
                member.ContactId = interest.Contact__c;
                contactMemberMap.put(interest.Contact__c, member);
            }
             if (interest.Lead__c != null && !leadMemberMap.keySet().contains(interest.Lead__c)) {
                member.LeadId = interest.Lead__c;
                leadMemberMap.put(interest.Lead__c, member);
            }
        }

        for (CampaignMember member : [Select Status, ContactId From CampaignMember 
            WHERE ContactId In : contactMemberMap.keySet() and CampaignId = :campaignMember.CampaignId]) {
                CampaignMember updateMember = contactMemberMap.get(member.ContactId);
                updateMember.Id = member.Id;
                if (!overwrite)
                    updateMember.Status = member.Status;
        }
 
        for (CampaignMember member : [Select Status, LeadId From CampaignMember 
            WHERE LeadId In : leadMemberMap.keySet() and CampaignId = :campaignMember.CampaignId]) {
                CampaignMember updateMember = leadMemberMap.get(member.LeadId);
                updateMember.Id = member.Id;
                if (!overwrite)
                    updateMember.Status = member.Status;
        }
 
 		String contatcNames = '';
        for (Contact contact : [Select Name From Contact where Id In :contactMemberMap.keySet()])  {
        	contatcNames += contact.Name + ', ';
        }
        
        if (contatcNames.length() > 2) {
        	contatcNames = contatcNames.substring(0, contatcNames.length() - 2);
        }
 
  		String leadNames = '';
        for (Lead lead : [Select Name From Lead where Id In :leadMemberMap.keySet()])  {
        	leadNames += lead.Name + ', ';
        }
        
        if (leadNames.length() > 2) {
        	leadNames = leadNames.substring(0, leadNames.length() - 2);
        }
        
        upsert contactMemberMap.values();
        upsert leadMemberMap.values();
        string msg = 'You have added ';
        if (contactMemberMap.size() > 0)
        	msg += contactMemberMap.size() + ' contacts ';
        if (leadMemberMap.size() > 0)
        	msg += leadMemberMap.size() + ' leads ';
        
        msg += ' to the campaign. ';
        
        if (contactMemberMap.size() > 0)
        	msg += 'The contacts are ' + contatcNames + '. ';
        
        if (leadMemberMap.size() > 0)
        	msg += 'The leads are ' + leadNames + '. ';
      
        MessageUtil.writeInfo(msg);
        return null;
    }
}