objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassObjectInterestUpdateExtTest.cls
@isTest
public class MassObjectInterestUpdateExtTest {

    static testMethod void testMassObjectInterestUpdateExt() {
		test.startTest();
 	  	MassActionTestFactory.setTestData();
  		Interest_Setup__c interestSetup = [Select Id, Name, Category__c From Interest_Setup__c LIMIT 1]; 
 
  		Contact contact = [Select Id From Contact LIMIT 1]; 

 		ApexPages.StandardController controller = new ApexPages.StandardController(contact);
 		
	  	MassObjectInterestUpdateExt  extension = new MassObjectInterestUpdateExt(controller);   
 
 		extension.getInterestWrappers();
 		
 		extension.saveInterests();
 		ApexPages.currentPage().getParameters().put('rowId', '0');
 		extension.removeInterest();
 		extension.addInterest();
  		extension.close(); 		
 
   		Lead lead = [Select Id From Lead LIMIT 1]; 
				
 		controller = new ApexPages.StandardController(lead);
 		
	  	extension = new MassObjectInterestUpdateExt(controller);   
 
 		extension.getInterestWrappers();

 		extension.saveInterests();
  		ApexPages.currentPage().getParameters().put('rowId', '0');
 		extension.removeInterest();
  		extension.addInterest();
 		extension.close(); 		 
 		test.stopTest();

 		System.assertEquals(extension != null, true);
    }
}