objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterestMassEmailExtTest.cls
@isTest
private class InterestMassEmailExtTest {

	static Interest_Setup__c interestSetup;	
	static void setup() {
		interestSetup = new Interest_Setup__c(Name='Basketball', Category__c='Sports');
		insert interestSetup;
	}

    static testMethod void testGetTemplates() {
 		test.startTest();
    	InterestMassEmailExt extension = getExtension();
    	List<SelectOption> templates = extension.getTemplates();
    	test.stopTest();
		System.assertEquals(templates != null, true);
    }
    
    static testMethod void testSendEmails() {
		test.startTest();
 	  	InterestMassEmailExt extension = getExtension();
 		extension.controller.setSelected([Select Id From Interest__c]);
		extension.sendEmails();
    	test.stopTest();
		System.assertEquals(extension != null, true);
    }
    
    static InterestMassEmailExt getExtension() {
 	  	MassActionTestFactory.setTestData();
 	  	InterestMassEmailExt extension = new InterestMassEmailExt(new ApexPages.StandardSetController([ Select Id From Interest__c]));   
 
    	//Folder folder = [Select Id from Folder Limit 1];
//    	Folder folder = new Folder(Name='Test', Type='Email');
    	//insert folder;
    	//EmailTemplate template = new EmailTemplate(Name='Test Template', DeveloperName='Test',
    	//							TemplateType='text', FolderId=folder.Id, isActive=true);
    	//insert template;
    	EmailTemplate template = [Select Id from EmailTemplate LIMIT 1];
    	extension.emailTemplateId = template.Id;

 		extension.controller.setSelected([Select Id From Interest__c]);
 		return extension;   	
    }
}