objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ObjectAddToInterestsExtTest.cls
@isTest
public class ObjectAddToInterestsExtTest {

    static testMethod void testObjectAddToInterestsExt() {
		test.startTest();
 	  	MassActionTestFactory.setTestData();
  		Interest_Setup__c interestSetup = [Select Id, Name, Category__c From Interest_Setup__c LIMIT 1]; 
 
 		List<Contact> contacts = [Select Id From Contact];
	  	ObjectAddToInterestsExt  extension = new ObjectAddToInterestsExt(
	  		new ApexPages.StandardSetController(contacts));   
	  	extension.interestWrappers[0].interest.Interest_Setup__c = interestSetup.Id;
	  	extension.controller.setSelected(contacts);	  	
		extension.saveInterests();
		extension.addInterestSetup();
		ApexPages.currentPage().getParameters().put('rowId', '0');
 		extension.removeInterestSetup();
		
		List<Lead> leads = [Select Id From Lead];
	  	extension = new ObjectAddToInterestsExt(
	  		new ApexPages.StandardSetController(leads));
	  	extension.interestWrappers[0].interest.Interest_Setup__c = interestSetup.Id;
	  	extension.controller.setSelected(leads);
		extension.saveInterests(); 
		extension.addInterestSetup();
		ApexPages.currentPage().getParameters().put('rowId', '0');
 		extension.removeInterestSetup();

 		test.stopTest();
		System.assertEquals(extension != null, true);
    }
}