objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterestWrapperTest.cls
@isTest
private class InterestWrapperTest {

	static Lead lead;
	static Contact contact;
	static Interest_Setup__c interestSetup;
	static Interest__c interest;
	
	static void setup() {
		interestSetup = new Interest_Setup__c(Name='Basketball', Category__c='Sports');
		insert interestSetup;
		contact = new Contact(LastName='ContactName');
		insert contact;
		lead = new Lead(LastName='LeadName', Company='Company', Status='Open - Not Contacted');
		insert lead;
	
		interest = new Interest__c(Contact__c = contact.Id, Interest_Setup__c = interestSetup.Id);
	}

    static testMethod void testDefaultConstructor() {
    	InterestWrapper wrapper = new InterestWrapper(interest);
    	System.AssertEquals(wrapper.interest, interest);
   		System.AssertEquals(wrapper.selected, false);
   		System.AssertEquals(wrapper.changed, false);
    	
    }

    static testMethod void testConstructorWithRowId() {
    	InterestWrapper wrapper = new InterestWrapper(interest, 100);
    	System.AssertEquals(wrapper.interest, interest);
   		System.AssertEquals(wrapper.selected, false);
   		System.AssertEquals(wrapper.changed, false);
   		System.AssertEquals(wrapper.rowId, 100);
   	
    }
}