objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassEditInterestsControllerTest.cls
@isTest
public class MassEditInterestsControllerTest {

    static testMethod void testMassEditInterestsController() {
		test.startTest();
 	  	MassActionTestFactory.setTestData();
  		Interest_Setup__c interestSetup = [Select Id, Name, Category__c From Interest_Setup__c LIMIT 1]; 
 		ApexPages.currentPage().getParameters().put('interestId', interestSetup.Id);
 		ApexPages.currentPage().getParameters().put('Name', interestSetup.Name);
 		ApexPages.currentPage().getParameters().put('Category', interestSetup.Category__c);

	  	MassEditInterestsController controller = new MassEditInterestsController();   
 		List<InterestWrapper> wrappers = controller.getInterestWrappers();
 		controller.previous();
 		controller.next();
 		controller.getHasNext();
 		controller.getHasPrevious();
 		controller.selectAll();
 		controller.close();
 		controller.deleteInterests();
 		controller.saveInterests();
 		
 		test.stopTest();
 		System.assertEquals(controller != null, true);
    }
}