objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassActionTestFactory.cls
public class MassActionTestFactory {
   public static void setTestData() {
		Interest_Setup__c interestSetup = new Interest_Setup__c(Name='Basketball', Category__c='Sports');
		insert interestSetup;
	
    	Lead lead1 = new Lead(FirstName='First1', LastName='Lead', Company='Company', 
    					Status='Open - Not Contacted', Email='test1@email.com');
    	insert lead1;
    	Lead lead2 = new Lead(FirstName='First2', LastName='Lead', Company='Company', 
    					Status='Open - Not Contacted', Email='test2@email.com');
    	insert lead2;
    	
    	insert new Interest__c(Lead__c = lead1.Id, Interest_Setup__c = interestSetup.Id);
    	
    	insert new Interest__c(Lead__c = lead2.Id, Interest_Setup__c = interestSetup.Id);

    	Contact contact1 = new Contact(FirstName='First1', LastName='Contact', Email='test1@email.com');
    	insert contact1;
    	Contact contact2 = new Contact(FirstName='First2', LastName='Contact', Email='test2@email.com');
    	insert contact2;
    	
    	insert new Interest__c(Contact__c = contact1.Id, Interest_Setup__c = interestSetup.Id);
     	
    	insert new Interest__c(Contact__c = contact2.Id, Interest_Setup__c = interestSetup.Id);
		
     }
}