objects/Interest__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Interest_Setup__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>Like</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t Like</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Setup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interest Setup</label>
        <referenceTo>Interest_Setup__c</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interests</relationshipLabel>
        <relationshipName>Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Interest</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interest_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifestyle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alma Mater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorite Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favoriate Vacation Spot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interest Setup</label>
    <nameField>
        <label>Interest Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassObjectInterestUpdateExt.cls
public with sharing class MassObjectInterestUpdateExt {

    private ApexPages.StandardController controller;
 
    protected List<InterestWrapper> interestWrappers = new List<InterestWrapper>();
    
    public MassObjectInterestUpdateExt(ApexPages.StandardController controller) {
        this.controller = controller;
        loadInterests();
    }
    
    private void loadInterests() {
        List<Interest__c> interests;
        if (controller.getRecord() instanceof Lead)
        	interests = [Select Notes__c, Name, Interest_Setup__c, Id, Degree__c, Lead__c, Category__c From Interest__c WHERE Lead__c = :controller.getRecord().Id];
        else
			interests = [Select Notes__c, Name, Interest_Setup__c, Id, Degree__c, Contact__c, Category__c From Interest__c WHERE Contact__c = :controller.getRecord().Id];        
        
        interestWrappers.clear();
        for (Integer index = 0; index < interests.size(); index++){
        	System.debug('load: ' + interests[index].Interest_Setup__c);
            interestWrappers.add(new InterestWrapper(interests[index], index));
        }
    }    
 
    public List<InterestWrapper> getInterestWrappers() {
        return interestWrappers;
    }
    
    public void addInterest() {
    	if (controller.getRecord() instanceof Lead)
    		interestWrappers.add(new InterestWrapper(new Interest__c(Lead__c = controller.getRecord().Id), interestWrappers.size()));
    	else 
    	   	interestWrappers.add(new InterestWrapper(new Interest__c(Contact__c = controller.getRecord().Id), interestWrappers.size()));
    		
    }

    public void removeInterest() {
        Integer rowId = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowId'));
        if (interestWrappers[rowId].interest.Id != null) {
            delete interestWrappers[rowId].interest; 
        }
        
        interestWrappers.remove(rowId);
        for (Integer index = 0; index < interestWrappers.size(); index++) {
            interestWrappers[index].rowId = index;
        }
        
    }
    
    public void saveInterests() {
        List<Interest__c> interests = new List<Interest__c>();
        
        Set<String> interestNameSet = new Set<String>();		
        for (InterestWrapper interestWrapper : interestWrappers) {
            interests.add(interestWrapper.interest);
        	System.debug('load: ' + interestWrapper.interest.Interest_Setup__c);
             if (interestNameSet.contains(interestWrapper.interest.Interest_Setup__c)) {
            	Interest_Setup__c setup = [SELECT Name FROM Interest_Setup__c where ID = :interestWrapper.interest.Interest_Setup__c limit 1];
            	MessageUtil.writeInfo(setup.Name + ' is duplicated. Save aborted.');
            	return;
            }
            interestNameSet.add(interestWrapper.interest.Interest_Setup__c);
        }
        
        if (interests.size() > 0) {
	        upsert interests;
	        MessageUtil.writeInfo('Interests are saved.');
        }
        loadInterests();
    }

    public PageReference close() {
    	return new PageReference('/' + controller.getRecord().Id);
    	
    }
}